### PR TITLE
Added the Hogwarts Sorting Hat

### PR DESCRIPTION
**Pull request by marty331**

### CODE REVIEW

**Comment by kushagra10025** [comment]
@marty331 This was really great, with the integration and updating the documentation too.
And anybody loves a good old Harry Potter reference in their CLI program. ✌
I'll take this opportunity to say.... **_"50 Points to Gryffindor"_** 😁

**Comment by marty331** [comment]
> @marty331 This was really great, with the integration and updating the documentation too. And anybody loves a good old Harry Potter reference in their CLI program. ✌ I'll take this opportunity to say.... **_"50 Points to Gryffindor"_** 😁

That's awesome!  I'm glad you liked it.  Do you have anything else you would like added?  I'm happy to pitch in and help out.

**Comment by kushagra10025** [comment]
@marty331 Really grateful for your pitch in. If you can help with abstracting the cpp_template.py file (TODO.md)
It'll be really helpful as I am new to python and don't really know how class work in detail. 
Again the main purpose for this project of mine was to create a tool to quickly create a basic folder structure for my CPP projects.

**Comment by kushagra10025** [comment]
> @marty331 Really grateful for your pitch in. If you can help with abstracting the cpp_template.py file (TODO.md)
> It'll be really helpful as I am new to python and don't really know how class work in detail. 
> Again the main purpose for this project of mine was to create a tool to quickly create a basic folder structure for my CPP projects.

With the abstraction I'm hoping to add support for different languages starter project template creation.

**Pull request merged**
